name: CI
on:
  push:
    branches: ["main"]
  merge:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: make setup
      - name: format
        run: make format
      - name: lint
        run: make lint
      - name: test
        run: make test
