name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          make setup
          make test
